---
- name: Check current iptables_exporter version
  failed_when: false
  changed_when: false
  register: prometheus_iptables_exporter_bin_stat
  ansible.builtin.stat:
    path: "{{ prometheus_iptables_exporter_bin_path }}"

- name: Check current iptables_exporter version
  become: true
  when: prometheus_iptables_exporter_bin_stat.stat.exists
  failed_when: false
  changed_when: false
  register: prometheus_iptables_exporter_version_check
  ansible.builtin.command:
    cmd: "{{ prometheus_iptables_exporter_bin_path }} --version"

- name: Stop iptables_exporter
  when: prometheus_iptables_exporter_bin_stat.stat.exists
  ignore_errors: true
  ansible.builtin.service:
    name: "{{ prometheus_iptables_exporter_name }}"
    state: stopped
    enabled: false

- name: Download and decompress iptables_exporter into temporary location
  when:
    not prometheus_iptables_exporter_bin_stat.stat.exists
    or
    prometheus_iptables_exporter_version_check.stdout is not defined
    or
    prometheus_iptables_exporter_version not in prometheus_iptables_exporter_version_check.stdout
  ansible.builtin.unarchive:
    src: "{{ prometheus_iptables_exporter_download_url | replace(' ', '') }}"
    dest: /tmp
    remote_src: true

- name: Move iptables_exporter binary into place
  become: true
  when:
    not prometheus_iptables_exporter_bin_stat.stat.exists
    or
    prometheus_iptables_exporter_version_check.stdout is not defined
    or
    prometheus_iptables_exporter_version not in prometheus_iptables_exporter_version_check.stdout
  ansible.builtin.copy:
    src: /tmp/{{ prometheus_iptables_exporter_name }}
    dest: "{{ prometheus_iptables_exporter_bin_path }}"
    mode: "0755"
    remote_src: true

- name: Create iptables_exporter user
  become: true
  ansible.builtin.user:
    name: "{{ prometheus_iptables_exporter_name }}"
    shell: /sbin/nologin
    state: present

- name: Create iptables_exporter systemd unit file
  become: true
  when: ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: exporter.service.j2
    dest: /etc/systemd/system/{{ prometheus_iptables_exporter_name }}.service
    mode: "0644"
    owner: root
    group: root

- name: Create iptables_exporter sysv init file
  become: true
  when: ansible_service_mgr == "sysvinit"
  ansible.builtin.template:
    src: exporter.j2
    dest: /etc/init.d/{{ prometheus_iptables_exporter_name }}
    mode: "0644"
    owner: root
    group: root

# - name: "sysvinit enable"
#   when: ansible_service_mgr == "sysvinit"
#   ansible.builtin.command:
#     cmd: "chkconfig {{ prometheus_iptables_exporter_name }} on"

- name: Systemd daemon-reload
  become: true
  when: ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure iptables_exporter is started
  become: true
  ansible.builtin.service:
    name: "{{ prometheus_iptables_exporter_name }}"
    enabled: true
    state: started
