---
- name: Stop iptables_exporter container
  become: true
  ignore_errors: true
  community.docker.docker_container:
    name: iptables_exporter
    state: stopped

- name: Remove iptables_exporter container
  become: true
  ignore_errors: true
  community.docker.docker_container:
    name: iptables_exporter
    state: absent
