---
- name: Stop iptables_exporter
  ignore_errors: true
  ansible.builtin.service:
    name: "{{ prometheus_iptables_exporter_name }}"
    state: stopped
    enabled: false

- name: Remove iptables_exporter.service
  when: ansible_service_mgr == "systemd"
  ansible.builtin.file:
    path: /etc/systemd/system/{{ prometheus_iptables_exporter_name }}.service
    state: absent

- name: Systemd daemon-reload
  when: ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Remove iptables_exporter user
  ansible.builtin.user:
    name: "{{ prometheus_iptables_exporter_name }}"
    state: absent

- name: Remove iptables_exporter executable
  ansible.builtin.file:
    path: /usr/local/bin/{{ prometheus_iptables_exporter_name }}
    state: absent
