---
- name: Install iptables_exporter
  when:
    - deploy_iptables_exporter is defined
    - deploy_iptables_exporter == "install"
  block:
    - name: Include tasks for docker install iptables_exporter
      when:
        - deploy_iptables_exporter_mode is defined
        - deploy_iptables_exporter_mode == "docker"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_docker.yml

    - name: Include tasks for binary install iptables_exporter
      when:
        - deploy_iptables_exporter_mode is defined
        - deploy_iptables_exporter_mode == "binary"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/install_binary.yml

    - name: Verify iptables_exporter is responding to requests
      register: metrics_output
      failed_when: "'iptables_scrape_success' not in metrics_output.content"
      retries: 6
      delay: 60
      ansible.builtin.uri:
        url: http://127.0.0.1:{{ prometheus_iptables_exporter_port }}/metrics
        return_content: true


- name: Uninstall iptables_exporter
  when:
    - deploy_iptables_exporter is defined
    - deploy_iptables_exporter == "uninstall"
  block:
    - name: Include tasks for docker uninstall iptables_exporter
      when:
        - deploy_iptables_exporter_mode is defined
        - deploy_iptables_exporter_mode == "docker"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_docker.yml

    - name: Include tasks for binary uninstall iptables_exporter
      when:
        - deploy_iptables_exporter_mode is defined
        - deploy_iptables_exporter_mode == "binary"
      ansible.builtin.include_tasks:
        file: tasks/sub-tasks/uninstall_binary.yml
